### ISSUE TITLE
Backup every minute

### ISSUE THREAD

**Issue by dogbrain** [Kaiede/BedrockifierCLI#2]
I have a docker file with the following settings for the backup:

backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "bedrock_axel"
    environment:
        BACKUP_INTERVAL: "3h"
        TZ: "Europe/Stockholm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./axel_data:/bedrock_axel

for some reason it makes an backup each minute since a couple of weeks back. Has been working great and flawlessly for months.

Have something changed that might have caused that or could it be some other reason forthe new beahviour

**Comment by Kaiede** [comment]
1.18 changed one of the strings that the tool depends on, unfortunately. This PR fixed the string: #1 

You’ll want to `docker-compose down`, run `docker pull kaiede/minecraft-bedrock-backup`, and bring it back up with `docker-compose up -d` again. Fixes unfortunately don’t get pushed out to clients automatically. 

I need to make some other changes to better handle the scenario so docker doesn’t think the container is unhealthy and re-start it constantly when stuff like this happens.

**Comment by dogbrain** [comment]
Thanks for the fast reply! Keep up the good job!

**Comment by Kaiede** [comment]
I’ve also opened up an issue to track the improvements to avoid this sort of recurring behavior: https://github.com/Kaiede/docker-minecraft-bedrock-backup/issues/13

Mostly just needs testing on my local server for a bit before I merge the changes.
